spring.application.name=ProyectoFinalBack

#Mail Service
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bosquebank@gmail.com
spring.mail.password=zfoaznnshkwnfsev
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# PostgreSQL (Michael)
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=1234

# PostgreSQL (Santiago)
spring.datasource.url=jdbc:postgresql://192.168.56.130:5432/bosquebank_db
spring.datasource.username=vm_bosquedb
spring.datasource.password=123456

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect